CREATE TABLE cvs (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	filepath VARCHAR(500) NOT NULL,
	upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE job_descriptions (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	filepath VARCHAR(500) NOT NULL,
	upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE analyses (
	id SERIAL PRIMARY KEY,
	cv_id INTEGER REFERENCES cvs(id) ON DELETE CASCADE,
	jd_id INTEGER REFERENCES job_descriptions(id) ON DELETE CASCADE,
	result_json JSONB,
	analyzed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(cv_id, jd_id)
);
